eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
server:
  port: 8761
spring:
  application:
    name: naming-server
