apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: naming-server
  name: naming-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: naming-server
  template:
    metadata:
      labels:
        app: naming-server
    spec:
      containers:
        - image: pollitodev/spring-cloud-v2-naming-server:0.1.0-SNAPSHOT
          name: spring-cloud-v2-naming-server
          resources:
            limits:
              cpu: 300m
              ephemeral-storage: 1Gi
              memory: 700Mi
            requests:
              cpu: 250m
              ephemeral-storage: 1Gi
              memory: 500Mi
          securityContext:
            capabilities:
              drop:
                - NET_RAW
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: naming-server
  name: naming-server
  namespace: default
spec:
  ports:
    - port: 8761
      protocol: TCP
      targetPort: 8761
  selector:
    app: naming-server
  type: ClusterIP
